Repository raytracingDevTeam/raytracing, pull requests merged in 2018-06, with the labels that each got.

#54 Feature/instancing
  src/CMakeLists.txt
  src/hitable.h
  src/main.cpp
  src/rect.h
  src/sphere.h
Labels: feature

#58 Added light material.
  run.sh
  src/hitable.h
  src/main.cpp
  src/material.h
  src/rect.h
  src/sphere.h
Labels: feature

#60 Bugfix/image texture uv
  run.sh
  src/main.cpp
  src/material.h
  src/sphere.h
Labels: bug

#61 Bugfix/removed warnings
  .gitignore
  .travis.yml
  README.MD
  appveyor.yml
  resource/render_0001.png
  resource/sample_texture.jpg
  resource/sample_texture.png
  run.sh
  src/color.h
  src/hitablelist.h
  src/main.cpp
  src/parser.h
  src/sphere.h
  src/texture.h
Labels: bug, feature
